name: Deploy React App to VPS

on:
    push:
        branches: [main] # Change if you deploy from another branch

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production # ✅ Updated environment

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Write env file
              run: echo "${{ secrets.VITE_FORMSPREE_APIKEY }}" | base64 -d > .env

            - name: Debug env
              run: cat .env

            - name: Install dependencies
              run: npm ci

            - name: Build Vite app
              # run: npm run build # Vite builds into `dist/`
              run: npm run build -- --mode production # The -- passes the extra flag to the npm script. This tells Vite to explicitly load .env.production.

            - name: Upload source code to VPS
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  source: '.'
                  target: '/home/${{ secrets.VPS_USER }}/apps/reactapp'

            - name: Prepare VPS directory
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      sudo rm -rf /var/www/html
                      sudo mkdir -p /var/www/html
                      sudo chown $USER:$USER /var/www/html

            - name: Upload dist folder via SCP
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  # // dist/* will miss nested folders and dotfiles
                  # source: 'dist/*'
                  source: 'dist/.'
                  # 'dist/.' tells SCP to upload everything inside the dist folder (including dotfiles, nested folders, etc.) but not the dist directory itself.
                  target: '/var/www/html'
                  strip_components: 1

            # - name: SSH to VPS and build
            #   uses: appleboy/ssh-action@v0.1.8
            #   with:
            #       host: ${{ secrets.VPS_HOST }}
            #       username: ${{ secrets.VPS_USER }}
            #       key: ${{ secrets.VPS_SSH_KEY }}
            #       script: |
            #           # Move to app directory
            #           cd ~/apps/reactapp

            #           # Copy your stored .env.production into place
            #           cp ~/reactapp-deploy-secrets/.env.production .env.production

            #           # Install or update nvm
            #           export NVM_DIR="$HOME/.nvm"
            #           if [ ! -d "$NVM_DIR" ]; then
            #             curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            #           fi
            #           source "$NVM_DIR/nvm.sh"

            #           # Install and use latest Node.js (auto includes npm)
            #           nvm install node --reinstall-packages-from=node
            #           nvm use node

            #           # Confirm versions (debugging)
            #           node -v
            #           npm -v

            #           # Install dependencies and build
            #           npm ci
            #           NODE_OPTIONS="--max-old-space-size=384" npm run build

            #           # Deploy to nginx directory
            #           sudo rm -rf /var/www/html/*
            #           sudo cp -r dist/* /var/www/html/

            #           # clean up app directory
            #           echo "Wiping ~/apps/reactapp completely after deploy..."
            #           sudo rm -rf ~/apps/reactapp/*

            - name: Reload Nginx (optional)
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      sudo systemctl reload nginx
